/* 
 * DG - GLS www.licence.nsw.gov.au
 * This is a private project and should be copied, modified, 
 * distributed without consent of GLS.
 * There are submodules and libraries used that may of be MIT, GP
 * and Lesser that are not affiliated in anyway with DG.
 * 
 * Filename: fish_str.en.js
 * Version: 1.0
 * 
 * Description:
 * 
 * English string file for fish feature.
 * 
 */

var fishStrEN = {
    // Custom strings
    D001: "Fishing Licence",
    D002: "Fisheries Details",
    D003: "<p>Agency Address: LMB 3020, NOWRA NSW 2541<br/>Agency Email: <a href='mailto:recfish.licensing@industry.nsw.gov.au'>recfish.licensing@industry.nsw.gov.au</a>Agency Phone: 02 4424 7400</p>",
    D004: "Pay NSW Fishing Fee",
    D005: "Home",
    D006: "Thank You",
    D007: "FISHING LICENCE",
    D008: "Processing Time",
    D009: "Instant",
    D010: "Cost",
    D011: "(Credit card surcharge applies)",
    D012: "Documents Required",
    D013: "None",
    D014: "Credit Cards Accepted",
    D015: "RESIDENTIAL ADDRESS",
    D016: "MAILING ADDRESS",
    D017: "Personal Details",
    D018: "Title",
    D019: "First Name",
    D020: "Please select...",
    D021: "Last Name",
    D022: "Date of Birth",
    D023: "Contact Details",
    D024: "Address",
    D025: "Residential Address",
    D026: "Same as <strong>Residential Address</strong>",
    D028: "DURATION",
    D029: "AMOUNT DUE",
    D030: "Cost Details",
    D031: "Duration & Fees",
    D032: "LICENCE START DATE",
    D033: "dd/mm/yyyy",
    D034: "Licence Fee",
    D035: "Credit Card Surcharge",
    D036: "Total Cost",
    D037: "Please select a valid date.",
    D038: "The licence start date must be within 27 days from today.",
    D039: "Please select a valid duration.",
    D040: "Terms",
    D041: "I accept the terms & conditions.",
    D042: "Confirm & Pay",
    D043: "Review Details",
    D044: "Full Name",
    D045: "Mailing Address",
    D046: "Duration",
    D047: "CC Payment",
    D048: "Total Amount Due",
    D049: "Full Name on Card",
    D050: "CVV",
    D051: "Pay",
    D052: "Confirm Payment",
    D053: "Tips",
    D054: "Card Number is the 16 digits on the front of your credit card.",
    D055: "The CVV2 Security Code is the last 3 digits usually on the back of your card. For AMEX, it is the 4 digit on the front of your card.",
    D056: "TOTAL AMOUNT PAYABLE",
    D057: "Please click 'OK' to proceed.",
    D058: "surcharge on",
    D059: "Amount payable includes a",
    D060: "The card you are using may not be supported.",
    D061: "Successful",
    D062: "Confirmation has been sent to your email and a plastic card will sent to you in the post.",
    D063: "Confirmation has been sent to your email.",
    D064: "Card Number",
    D065: "Expiry Date",
    D066: "Month",
    D067: "Year",
    D068: "SECURED BY SSL",
    D069: "Feedback",
    D070: "Comments",
    D071: "Tell us what you didn't like about our service today.",
    D072: "Tell us how we could make our service better.",
    D073: "Licence Start Date",
    D074: "Licence No",
    D075: "Issued To",
    D076: "Amount Paid",
    D077: "Applied On",
    D078: "Please rate your experience with the service used today.",
    D079: "Good",
    D080: "Average",
    D081: "Poor",
    D082: "Thank you for your time.",
    D083: "Thank you for your feedback. It will help us improve our services.",
    D084: "Payment Details",
    D085: "Fee",
    D086: "Surcharge",
    D087: "Grand Total",
    D088: '<div class="panel"><ul class="disc"><li>3 Days: <strong>$7</strong></li><li>1 Month: <strong>$14</strong></li><li>1 Year: <strong>$35*</strong></li><li>3 Years: <strong>$85*</strong></li></ul></div>',
    D089: "Tell us what you liked about our service today.",

    // Final Submission Messages
    D090: "Invalid credit card, please try again.",
    D091: "Processing ...",

    // Error messages
    E001: "Please enter your first name.",
    E002: "Please enter your last name.",
    E003: "Please select your date of birth.",
    E004: "You must be of 18 years of age or older to apply.",
    E005: "Please enter a valid email.",
    E006: "Please enter a valid mobile.",
    E007: "Please enter a valid address.",
    E008: "Please agree to our terms and conditions.",
    E009: "Please enter a valid credit card number.",
    E010: "Please select a month for the expiry date.",
    E011: "Please enter a year for the expiry date.",
    E012: "Please enter a valid CVV security code.",
    E013: "Please enter a valid name."
};